FROM nanodatacenter/bash_basic 
ENV CONTAINER_NAME "mqtt_to_db" 
ENV SERVER_ID      "mqtt_to_db"
ENV TEST_SERVER_ID "mqtt_to_db_test"
VOLUME [/data/] 

COPY ./mqtt_to_db .
COPY ./mqtt_test/mqtt_test .

