target:
	$(MAKE) -C  go_basic_container
	$(MAKE) -C  go_setup_containers
	$(MAKE) -C  go_service_containers
	$(MAKE) -C  site_control_app
	$(MAKE) -C  go_application_containers
	$(MAKE) -C  go_system_containers
	$(MAKE) -C  go_terminals

all: target
